//created on: May 15, 2015
package com.redhat.brms

import com.redhat.brms.Driver;
import com.redhat.brms.Quote;



rule "DriverAgeEligibilityRules"
dialect "mvel"
salience 100
ruleflow-group "EligibilityRule"
    when
        $d : Driver( age < 18 )
    then
        Quote quote = new Quote();
	    quote.setEligibility( "NO" );
	    insertLogical( quote )
end

rule "DriverCityEligibilityRules"
dialect "mvel"
salience 99
ruleflow-group "EligibilityRule"
    when
        $d : Driver( city == "Dallas" && zipCode == "54321" )
    then
        Quote quote = new Quote();
	    quote.setEligibility( "NO" );
	    insertLogical( quote )
end
